### ISSUE TITLE
Stop stalling Human Progress

### ISSUE THREAD

**Issue by mrx23dot** [psmedia/Books3Info#1]
AI cannot reproduce original content, thus it's no different than reading every book in the library for free.

**Comment by psmedia** [comment]
GenAI models reproduce original content all the time, though RLHF and system prompts try to suppress that behaviour. I'll grant you that the ways they represent content in the weights are super-interesting, and that they *also* abstract content. On the "no different than reading books" or the "AI Equivalence Fallacy", see Ed Newton-Rex - "It ignores (i) the scale & effect of generative AI and (ii) the implicit social contract under which people have created and published works for centuries."
